---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%"
)
```

# ggfancy

The goal of ggfancy is to create clean and helpful ggplots.

## Installation

You can install the development version from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("edo91/prettifier")
```

## Example

This is a basic example which shows you how to solve a common problem:

```{r example}
library(ggfancy)
## basic example code
```

### Pareto Chart
```{r}
test <- dplyr::sample_n(tibble::tibble(letters = letters),100, replace=TRUE)
test$frequency <- round(runif(100, 1, 5),0)
plot_pareto(test, letters, frequency, group_over = 6)
```

### Heatmap
```{r}
plot_heatmap(iris)

x <- tibble::as_tibble(setNames(purrr::rerun(6,
                                             sample(c(1:10,NA), 
                                                    100,
                                                    replace = TRUE)),
                                letters[1:6]))

plot_na(x)
```

### Waterfall
```{r}

aa <- tibble::tribble(
  ~ group  , ~ label      , ~ value,
  "season1", "loss"       ,     -20,
  "season1", "new"        ,      30,
  "season1", "gain"       ,      40,
  "season2", "loss"       ,     -15,
  "season2", "gain"       ,      25,
  "season3", "loss"       ,     -10,
  "season3", "disappeared",     -15,
  "season3", "gain"       ,       5
  
)

starting_point <- 100

plot_waterfall(aa, starting_point)

```

### ScatterMatrix
```{r}
plot_scattermatrix(iris)
```

### Silhoutte
```{r}
kcl <- kmeans(mtcars, centers = 5, nstart = 50)
dis <- dist(mtcars)^2
plot_silhouette(v_clusters = kcl$cluster, mx_dist = dis, threshold = 0.3)
```


